os: linux

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  include:
    - name: macOS
      os: osx
      language: generic
      before_install:
        - curl -s http://getcomposer.org/installer | php
        - mv composer.phar /usr/local/bin/composer
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer remove --dev vimeo/psalm; fi
  - composer update -n --prefer-dist
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then echo "Skipped psalm static analysis"; else vendor/bin/psalm; fi

after_script:
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
