os: linux
dist: xenial
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer remove --dev psalm/phar; fi
  - composer update -n --prefer-dist
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/coveralls.phar
  - chmod +x coveralls.phar

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - vendor/bin/psalm.phar

after_script:
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
